[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.1.0"
bs58 = "0.5.1"
ed25519-dalek = "2.1.1"
merlin = "3.0.0"
pem = "3.0.4"
rand = "0.8.5"
serde = "1.0.216"
signature = "2.2.0"
